export { Copy } from "./copy";
export { Cut } from "./cut";
export { Edit } from "./edit";
export { Image } from "./image";
export { Open } from "./open";
export { Paste } from "./paste";
export { Pause, Play, Spin } from "./play-pause";
export { Redo } from "./redo";
export { Save } from "./save";
export { Switch } from "./switch";
export { Text } from "./text";
export { Undo } from "./undo";
